name = "gond"
version = "2.0.1"
description = "🚡 multi-branch conditional expression similar to if - else if - else or cond for Gleam 🚠 (elseif, elif)"
licences = ["MPL-2.0"]
repository = { type = "github", user = "inoas", repo = "gleam-gond" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
